In [14]:
%matplotlib inline
import numpy as np

### FFT
There are many ways to define the DFT, varying in the sign of the exponent, normalization, etc. In this implementation, the DFT is defined as

$$A_k=a_m\sum_{m=0}^{n-1} {exp\{-2*\pi*i\frac {mk} {n}\}} $$         k=0,1,...,n-1

The values in the result follow so-called “standard” order: If A = fft(a, n), then **A[0]** contains the zero-frequency term (the sum of the signal), which is always purely real for real inputs. 

Then **A[1:n/2]** contains the positive-frequency terms, and **A[n/2+1:]** contains the negative-frequency terms, in order of decreasingly negative frequency. 

### 偶数输入点
For an even number of input points, A[n/2] represents both positive and negative Nyquist frequency, and is also purely real for real input. 

### 奇数输入点
For an odd number of input points, A[(n-1)/2] contains the largest positive frequency, while A[(n+1)/2] contains the largest negative frequency. 

### Normalization
The default normalization has the direct transforms **unscaled** and the inverse transforms are scaled by **1/n**. It is possible to obtain unitary transforms by setting the keyword argument norm to "ortho" (default is None) so that both direct and inverse transforms will be scaled by $1/\sqrt{n}$.

### 计算效率
FFT (Fast Fourier Transform) refers to a way the discrete Fourier Transform (DFT) can be calculated efficiently, by using symmetries in the calculated terms. The symmetry is highest when **n is a power of 2**, and the transform is therefore most efficient for these sizes.

### 幅度
When the input a is a time-domain signal and A = fft(a), np.abs(A) is its amplitude spectrum and np.abs(A)**2 is its power spectrum. The phase spectrum is obtained by np.angle(A).

### rfft
When the DFT is computed for purely real input, the output is Hermitian-symmetric, i.e. the negative frequency terms are just the complex conjugates of the corresponding positive-frequency terms, and the negative-frequency terms are therefore redundant. This function does not compute the negative frequency terms, and the length of the transformed axis of the output is therefore **n/2 + 1**.

When A = rfft(a) and fs is the sampling frequency, A[0] contains the zero-frequency term 0*fs, which is real due to Hermitian symmetry.

If n is even, A[-1] contains the term representing both positive and negative Nyquist frequency (+fs/2 and -fs/2), and must also be purely real. If n is odd, there is no term at fs/2; A[-1] contains the largest positive frequency (fs/2*(n-1)/n), and is complex in the general case.

### 偶数个点
If n is even, the length of the transformed axis is (n/2)+1. 

### 奇数个点
If n is odd, the length is (n+1)/2.

### Real and Hermitian transforms 
When the input is purely real, its transform is **Hermitian**, i.e., the component at frequency $f_k$ is the complex conjugate of the component at frequency $-f_k$, which means that for real inputs there is no information in the negative frequency components that is not already available from the positive frequency components. 

The family of $\color{red}{rfft}$ functions is designed to operate on real inputs, and exploits this symmetry by computing only the positive frequency components, up to and including the Nyquist frequency. Thus, n input points produce **n/2+1** complex output points. The inverses of this family assumes the same symmetry of its input, and for an output of n points uses **n/2+1** input points.

Correspondingly, when the spectrum is purely real, the signal is **Hermitian**. The hfft family of functions exploits this symmetry by using n/2+1 complex points in the input (time) domain for n real points in the frequency domain.

### 频率
The routine np.fft.fftfreq(n) returns an array giving the frequencies of corresponding elements in the output. 

### shift
The routine np.fft.fftshift(A) shifts transforms and their frequencies to put the zero-frequency components in the middle, and np.fft.ifftshift(A) undoes that shift.

When the input a is a time-domain signal and A = fft(a), np.abs(A) is its amplitude spectrum and np.abs(A)**2 is its power spectrum. The phase spectrum is obtained by np.angle(A).



### 偶数个数据

In [15]:
a=np.asarray([0,1,0,0])

### fft 函数

In [16]:
b=np.fft.fft(a)

In [17]:
b

array([ 1.+0.j,  0.-1.j, -1.+0.j,  0.+1.j])

### rfft 函数

In [18]:
c=np.fft.rfft(a)

In [19]:
c

array([ 1.+0.j,  0.-1.j, -1.+0.j])

长度为4/2+1=3

### 奇数个数据

In [20]:
a=np.asarray([0,1,0,0,1])

In [21]:
b=np.fft.fft(a)

In [22]:
b

array([ 2.00000000+0.j,  0.61803399+0.j, -1.61803399+0.j, -1.61803399+0.j,
        0.61803399+0.j])

In [23]:
c=np.fft.rfft(a)

In [24]:
c

array([ 2.00000000+0.j,  0.61803399+0.j, -1.61803399+0.j])

长度为(5+1)/2=3